### ISSUE TITLE
사이트에 들어가지지 않습니다.

### ISSUE THREAD

**Issue by sappho192** [nanikit/dc-highlighter#1]
안녕하세요,
종종 여기서 Github Pages로 서비스되고 있는 코드 하이라이터를 잘 쓰고 있었는데요,
오늘 아래 사이트에 들어가려고 하니 404 에러가 나오면서 접근이 되지 않았습니다.
https://nanikit.github.io/dc-highlighter/
혹시 일부러 서비스를 닫으신건가요?

**Comment by nanikit** [comment]
복구했습니다. 왜인지 없는 브랜치가 등록되어 있었네요.

**Comment by sappho192** [comment]
감사합니다.
